# Generated by Django 3.2.9 on 2022-03-01 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20220228_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='credithour',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='reservehour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='unreadcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
