# Generated by Django 3.2.9 on 2022-03-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220301_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credithour',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reservehour',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unreadcount',
        ),
    ]
