# Generated by Django 3.2.9 on 2022-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220301_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
