# Generated by Django 3.2.9 on 2022-03-04 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='service_pics/default.png', upload_to='service_pics')),
                ('servicedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=1)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=100)),
                ('eventcontent', models.TextField()),
                ('eventdate_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='event_pics/default.png', upload_to='event_pics')),
                ('eventdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
