# Generated by Django 3.2.9 on 2022-01-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_emodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EModel',
        ),
    ]
