# Generated by Django 3.2.9 on 2022-03-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='picture',
            new_name='image',
        ),
    ]
